swagger-ui:
  image: swaggerapi/swagger-ui
  container_name: "swagger-ui-container"
  ports:
    - "8081:8080"
  volumes:
    - ./*.yaml:/swagger_data
  environment:
    SWAGGER_JSON: swagger_data/*.yaml

swagger-editor:
  image: swaggerapi/swagger-editor
  container_name: "swagger-editor-container"
  ports:
    - "8082:8080"
